src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(
     *      message = "Ce champs ne peut pas rester vide"
     * )
     * @Assert\Length(
     *      min=2,
     *      max=255,
     *      minMessage="Le titre d'un article doit comporter au moins {{ limit }} caractères",
     *      maxMessage="Let titre d'un article doit comporter au plus {{ limit }} caractères"
     * )
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(
     *      message = "Ce champs ne peut pas rester vide"
     * )
     * @Assert\Length(
     *      min=2,
     *      max=255,
     *      minMessage="Le contenu d'un article doit comporter au moins {{ limit }} caractères",
     *      maxMessage="Let contenu d'un article doit comporter au plus {{ limit }} caractères"
     * )
     */
    private $contenu;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_de_creation;

    /**
     * @ORM\Column(type="integer")
     */
    private $votes = 0;

    /**
     * @ORM\Column(type="integer")
     */
    private $votes_up = 0;

    /**
     * @ORM\Column(type="integer")
     */
    private $votes_down = 0;

    /**
     * @ORM\Column(type="integer")
     */
    private $votes_total = 0;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank(
     *      message = "Ce champs ne peut pas rester vide"
     * )
     *
     */
    private $category;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getDateDeCreation(): ?DateTime
    {
        return $this->date_de_creation;
    }

    public function setDateDeCreation(DateTime $date_de_creation): self
    {
        $this->date_de_creation = $date_de_creation;

        return $this;
    }

    public function getVotes(): ?int
    {
        return $this->votes;
    }

    public function setVotes(int $votes): self
    {
        $this->votes = $votes;

        return $this;
    }

    
    

    public function getVotesUp(): ?int
    {
        return $this->votes_up;
    }

    public function setVotesUp(int $votes_up): self
    {
        $this->votes_up = $votes_up;

        return $this;
    }

    public function getVotesDown(): ?int
    {
        return $this->votes_down;
    }

    public function setVotesDown(int $votes_down): self
    {
        $this->votes_down = $votes_down;

        return $this;
    }

    public function getVotesTotal(): ?int
    {
        return $this->votes_total;
    }

    public function setVotesTotal(int $votes_total): self
    {
        $this->votes_total = $votes_total;

        return $this;
    }

    //Votes String
    public function getVotesString(): string 
    {
        $prefix = $this -> getVotes() >= 0 ? "+" : "-";
        return $prefix." ".abs($this -> getVotes());
    }

    //up / down vote
    //diff votes
    public function upVote()
    {
        return $this -> setVotes($this -> getVotes() + 1);
    }
    public function downVote()
    {
        return $this -> setVotes($this -> getVotes() - 1);
    }
    //nombre votes up
    public function nombreVotesUp()
    {
        return $this -> setVotesUp($this -> getVotesUp() + 1);
    }
    public function nombreVotesDown()
    {
        return $this -> setVotesDown($this -> getVotesDown() + 1);
    }
    //nombre votes total
    public function nombreVotesTotal()
    {
        return $this -> setVotesTotal($this -> getVotesTotal() + 1);
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;


class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        //création de champs avec type correspondant (exemple: type=text => TextType::class)
        $builder
            ->add('titre', TextType::class, array('help' => 'Veuillez introduire un titre pour le nouveau article'))
            ->add('contenu', TextType::class, array('help' => 'Veuillez introduire un contenu pour le nouveau article')) 
            //importer avec use pour pouvoir utiliser EntityType           
            ->add('category', EntityType::class, [
                // looks for choices from this entity Category
                'class' => Category::class,
                // uses the Category.name property as the visible option string
                'choice_label' => 'name',
                // used to render a select box, check boxes or radios
                'multiple' => false, // choice multiple true ou false
                'expanded' => false, //true => radio ou checkbox (selon multiple)
                'help' => 'Veuillez choisir une catégorie pour le nouveau article'
                ])
            ->add('submit', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use DateTime;
use App\Entity\Article;
use App\Entity\Category;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use Doctrine\ORM\EntityManagerInterface;


class ArticleController extends AbstractController
{
    //définition route 1 => affichage de touts les articles de la base de données
    /**
     * @Route("/article", name="article")
     */
    public function indexArticles(EntityManagerInterface $manager): Response {
        //$manager va appeler le repository
        //Fonction getRepository(classe_Entity::class) retourne un objet de la classe repository (ici un ArticleRepository)
        $repository = $manager -> getRepository(Article::class);
        //Avec l'objet repository vous pouvez appeler les fonctions définies dans la classe repository (ArticleRepository)
        $articles = $repository -> findAll();

        return $this->render('article/index.html.twig', [
            'articles' => $articles         
        ]);
    }
    
    //définition route 2 => choix de article pour voter
    /**
     * @Route("/article/vote/{number}", name="article_vote")
     */
    public function indexArticleDetail($number): Response
    {
        return $this->render('article/vote.html.twig', [
            'number' => $number,
            'votes' => rand(1, 100)            
        ]);
    }

    //définition route 3 => return JSON
    /**
     * @Route("article/actionVote", name="vote")
     */
    //IMPORTANT => cette route renvoie un réponse JSON, pas de traitement via TWIG (donc pas de render)
    public function indexArticleVote(): JsonResponse {
        //déclaration variable votes qui sera envoyer via JSON
        $tabInfo = ['votes' => rand(1, 100)];

        return new JsonResponse($tabInfo);
    
    }

    //définition route 4 => creation article et insertion BD
    /**
     * @Route("article/creation", name="article_creation")
     */
    public function indexArticleCreate(Request $request): Response {

        //création objet article
        $article = new Article();
        //création date de création
        $article -> setDateDeCreation(new DateTime());
        //string pour affichage
        $dateCreationString = $article -> getDateDeCreation() -> format('Y-m-d');

        //form
        //création objet form
        $form = $this -> createForm(ArticleType::class, $article);
        $form -> handleRequest($request);
        //si le form est submit et validé => récupération de données rentrée dans la variable $article
        if($form -> isSubmitted() && $form -> isValid()) {
            $article = $form -> getData();
            
            // insértion dans la base de données
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('affichage_article', [
                'id' => $article->getId()
                ]);
        }

        return $this->render('article/creationArticle.html.twig', [
            'form' => $form->createView()
            ]);
    }

    //définition route 5 => récupération des articles par année
    /**
     * @route("article/annee/{annee}", name="annee")
     */
    public function indexArticleAnnee($annee, ArticleRepository $manager): Response {

        $articles = $manager -> findbyYear($annee);       

        return $this->render('article/affichageArticleAnnee.html.twig', [
            'articles' => $articles,
            'annee' => $annee       
        ]);

    }


    //definition route 6 => récupération des articles qui contiennent le mot "magique" dans leur contenu
    /**
     * @route("article/content", name="affichage_article_magique")
     */
    public function indexArticleMagique(ArticleRepository $manager): Response {

        $articles = $manager -> findByContent('magique');

        return $this->render('article/affichageArticlesMag.html.twig', [
            'articles' => $articles         
        ]);
    }

    
    //définition route 7 => récupération des détails via une requête automatique (passer l'entity article comme paramétre)
    //EntityManager est appelé automatiquement! => pas besoin de l'appeler
    //ATTENTION: c'est un raccourci pour des requêtes simples
    /**
     * @route("article/id/{id}", name="affichage_article")
     */
    public function indexOneArticle(Article $article): Response {
     
        //Solution Entity Manager classique => pas besoin dans une requête automatique
        //$manager va appeler le repository
        //Fonction getRepository(classe_Entity::class) retourne un objet de la classe repository (ici un ArticleRepository)
        //$repository = $manager -> getRepository(Article::class);
        //Avec l'objet repository vous pouvez appeler les fonctions définies dans la classe repository (ArticleRepository)
        //$article = $repository -> find($id_article);
        //dd($articles);
        //traitement coleur affichage du score
        $class = "";
        $nombreVotes = $article -> getVotes();
        if( $nombreVotes > 0) {
            $class = "green";
        } else if ($nombreVotes < 0) {
            $class = "red";
        } else {
            $class= "orange";
        }

        return $this->render('article/affichageDetail.html.twig', [
            'article' => $article, 
            'class' => $class        
        ]);
    }

    //définition route 8 => votes
    /**
     * @route("article/votes/{id}", name="article_votes", methods="POST")
     */
    public function indexVotes(Article $article, Request $request, EntityManagerInterface $manager) {
        //récupération de la direction
        $direction = $request -> request -> get('direction');
        //actualisation valeur vote
        if($direction === "up") {
            $article -> upVote();
            $article -> nombreVotesUp();
        } elseif ($direction === "down") {
            $article -> downVote();
            $article -> nombreVotesDown();
        }

        $article -> nombreVotesTotal();

        //actualisation bd
        $manager -> flush();

        //traitement coleur affichage du score
        $class = "";
        $nombreVotes = $article -> getVotes();
        if( $nombreVotes > 0) {
            $class = "green";
        } else if ($nombreVotes < 0) {
            $class = "red";
        } else {
            $class= "orange";
        }

        //réaffichage vote actuelle
        return $this->render('article/affichageDetail.html.twig', [
            'article' => $article,
            'class' => $class        
        ]);
    }  
    
    //définition route 9 => affichage des articles par catégories
    /**
     * @route("article/category/{id}", name="article_categorie")
     */
    public function requeteParCategorie(Category $category): Response
    {
        $articles = $category -> getArticles();

        return $this->render('article/affichageArticlesCategorie.html.twig', [
            'articles' => $articles,
            'categorie' => $category                    
        ]);
    }

    

}

templates/article/affichageArticlesCategorie.html.twig
{% extends 'base.html.twig' %}

{% block title %}Affichage des articles par catégorie{% endblock %}

{% block body %}

<h1 class="titre_result">Affichage des articles pour la catégorie {{ categorie.getName() }}</h1>
<table class="table-titres table w-auto">
    <thead class="thead-dark">
        <tr>
            <th>Titres</th>
            <th>Nombre de votes</th>
        </tr>
    </thead>
    <tbody>
        {% for val in articles%}
        <tr>
            <td><a class="title-link" href="{{ path('affichage_article', {'id': val.id}) }}">{{ val.getTitre() }}</a></td>
            <td><p>{{ val.getVotesTotal() }}</p></td>             
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/article/affichageArticlesMag.html.twig
{% extends 'base.html.twig' %}

{% block title %}Affichage des articles magiques{% endblock %}

{% block body %}

<h1 class="titre_result">Affichage des articles magiques</h1>
<table class="table-titres table w-auto">
    <thead class="thead-dark">
        <tr>
            <th>Titres</th>
            <th>Nombre de votes</th>
        </tr>
    </thead>
    <tbody>
        {% for val in articles%}
        <tr>
            <td><a class="title-link" href="{{ path('affichage_article', {'id': val.id}) }}">{{ val.getTitre() }}</a></td>
            <td><p>{{ val.getVotesTotal() }}</p></td>             
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/article/affichageDetail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Affichage détail de l'article{% endblock %}

{% block body %}

    {% if article.getContenu() is empty %}

        <section class="affichage-detail-article-const">
            <h1>{{ article.getTitre() }} coming soon!</h1>
            <img class="img_construct" src="{{ asset('img/under_construction.jpg')}}" alt="under construction" title="under construction">
        </section>

    {% else %}
    
        <section class="affichage-detail-article">            
            <section class="detail-article"> 
                <h1>Détail de l'article {{ article.getId() }}</h1>               
                <h2>Titre</h2>
                <p>{{ article.getTitre() }}</p>
                <h2>Déscription</h2>
                <p>{{ article.getContenu() }}</p>
                <h2>Date de création</h2>
                <p>{{ article.getDateDeCreation()|date('d-M-Y') }}</p> 
                <h2>Catégorie</h2>
                <p>{{ article.getCategory().getName() }}</p>
            </section>                    
            <section class="form-votes">
                <h1>Voter pour l'article {{ article.getId() }}</h1>   
                <form action="{{ path('article_votes', {id: article.id}) }}" method="post">
                    <div class="form-votes-boutons">
                        <button class="votes-up btn btn-success" name="direction" value="up"><i class="fas fa-thumbs-up"></i></button>
                        <button class="votes-down btn btn-danger" name="direction" value="down"><i class="fas fa-thumbs-down"></i></button>
                    </div>
                </form>
            </section>
            <section>
                <h1>Résultat de votes</h1>
                <h3>Nombre total de votes</h3>
                <p class="votes-result">{{ article.getVotesTotal()}}</p>
                <h3>Nombre votes up</h3>           
                <p class="votes-result">{{ article.getVotesUp()}}</p>     
                <h3>Nombre votes down</h3>   
                <p class="votes-result">{{ article.getVotesDown()}}</p>             
                <h3>Score</h3>
                <p class="votes-result {{ class }}">{{ article.votesString}}</p>                
            </section>                        
        </section>

    {% endif %}

{% endblock %}

{% block javascripts%}
    {{ parent() }}
    <script src="{{ asset('js/vote.js')}}" type="text/javascript"></script>
{% endblock %}

templates/article/creationArticle.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article Création{% endblock %}

{% block body%}
    <h1 class="titre_creation">Création d'un nouveau article</h1>
    {# Form start#}
    {{ form_start(form) }}
    
    {# création des champs de formulaire#}
    <div class="form-section">
        {# contrôle si il y a des erreurs, si oui => ajout de la class "error" pour affichage en rouge#}
        <div {% if form.titre.vars.errors|length > 0 %}class="error"{% endif %}>
            {{ form_label(form.titre, 'Titre', {'label_attr': {'class': 'label-style'}}) }}
        </div>
        <p>{{ form_help(form.titre) }}</p>
        <div class="form-field">
            {{ form_widget(form.titre) }}
        </div>                    
    </div>    
    
    <div class="form-section">
        <div {% if form.contenu.vars.errors|length > 0 %}class="error"{% endif %}>
            {{ form_label(form.contenu, 'Contenu', {'label_attr': {'class': 'label-style'}}) }}
        </div>
        <p>{{ form_help(form.contenu) }}</p>
        <div class="form-field">
            {{ form_widget(form.contenu) }}
        </div>       
    </div>

    <div class="form-section">
        <div {% if form.category.vars.errors|length > 0 %}class="error"{% endif %}>
            {{ form_label(form.category,'Categorie', {'attr': {'label_class': 'label-style'}}) }}
        </div>
        <p>{{ form_help(form.category) }}</p>   
        <div class="form-field">
            {{ form_widget(form.category) }}
        </div>             
    </div>

    <div class="form-submit">
        {{ form_row(form.submit) }}
    </div>

    
    {{ form_end(form) }}
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Articles{% endblock %}

{% block body %}
<h1 class="titre_creation">Création nouveau article</h1>
{# vérification si l'utilisateur est connecté => si oui => création de l'article possible, sinon => form de login#}
<a class="title-link link_creation" {% if app.user %} href="{{ path('article_creation') }}" {% else %} href="{{ path('app_login') }}" {% endif %}>Nouveau article</a>
<h1>Affichage de tous les articles</h1>
<table class="table-titres table w-auto">
    <thead class="thead-dark">
        <tr>
            <th>Titres</th>
            <th>Nombre de votes</th>
        </tr>
    </thead>
    <tbody>
        {% for val in articles%}
        <tr>
            {# vérification si l'utilisateur est connecté => si oui => affichage de détail, sinon => form de login#}
            <td><a class="title-link" {% if app.user %} href="{{ path('affichage_article', {'id': val.id}) }}" {% else %} href="{{ path('app_login') }}" {% endif %}>{{ val.getTitre() }}</a></td> 
            <td><p>{{ val.getVotesTotal() }}</p></td>           
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/article/vote.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article Vote{% endblock %}

{% block body%}
    <section class="info-article">
        <h1>Détails sur l'article avec ID <span id="id_article">{{ number }}</span></h1>        
        <h3>Votes: <span id="nombre_votes">{{ votes }}</span></h3>
        <button id="votes_plus" class="btn btn-outline-dark">+</button>
        <button id="votes_moins" class="btn btn-outline-dark">-</button>    
    </section>
{% endblock %}

{% block javascripts%}
    {{ parent() }}
    <script src="{{ asset('js/vote.js')}}" type="text/javascript"></script>
{% endblock %}